// TYPES MENU PROJECT
export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECT = "GET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const CURRENT_PROJECT = "CURRENT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";


// TYPES TASK PROJECT

export const GET_TASKS = "GET_TASKS"